package workflows

import (
	"fmt"
	"time"
)

// ReportGenerator interface para geração de relatórios (evita import cycle)
type ReportGenerator interface {
	GenerateExecutiveReport(data interface{}, format string) (interface{}, error)
	GenerateDetailedReport(data interface{}, format string) (interface{}, error)
	GenerateAnomalyReport(data interface{}, format string) (interface{}, error)
}

// ReportingWorkflow implementa workflow para geração automática de relatórios
type ReportingWorkflow struct {
	*BaseWorkflow
	generator ReportGenerator
	config    *ReportingWorkflowConfig
}

// ReportingWorkflowConfig configurações do workflow de relatórios
type ReportingWorkflowConfig struct {
	AutoGenerateExecutive bool     `json:"auto_generate_executive"`
	AutoGenerateDetailed  bool     `json:"auto_generate_detailed"`
	AutoGenerateAnomaly   bool     `json:"auto_generate_anomaly"`
	DefaultFormats        []string `json:"default_formats"`
	SaveToFile           bool     `json:"save_to_file"`
	NotifyStakeholders   bool     `json:"notify_stakeholders"`
	OutputDirectory      string   `json:"output_directory"`
	EmailRecipients      []string `json:"email_recipients"`
}

// DefaultReportingWorkflowConfig retorna configuração padrão
func DefaultReportingWorkflowConfig() *ReportingWorkflowConfig {
	return &ReportingWorkflowConfig{
		AutoGenerateExecutive: true,
		AutoGenerateDetailed:  false,
		AutoGenerateAnomaly:   true,
		DefaultFormats: []string{
			"excel",
			"text",
		},
		SaveToFile:         true,
		NotifyStakeholders: false,
		OutputDirectory:    "./reports",
		EmailRecipients:    []string{},
	}
}

// NewReportingWorkflow cria novo workflow de relatórios
func NewReportingWorkflow(generator ReportGenerator, config *ReportingWorkflowConfig) *ReportingWorkflow {
	if config == nil {
		config = DefaultReportingWorkflowConfig()
	}
	
	steps := []WorkflowStep{
		NewDataPreparationStep(),
		NewExecutiveReportStep(generator, config),
		NewDetailedReportStep(generator, config),
		NewAnomalyReportStep(generator, config),
		NewReportSummaryStep(),
		NewNotificationStep(config),
	}
	
	baseWorkflow := NewBaseWorkflow(
		"intelligent-reporting",
		"Workflow para geração automática de relatórios inteligentes",
		steps,
	)
	
	return &ReportingWorkflow{
		BaseWorkflow: baseWorkflow,
		generator:    generator,
		config:       config,
	}
}

// DataPreparationStep prepara dados para geração de relatórios
type DataPreparationStep struct {
	*BaseStep
}

// NewDataPreparationStep cria step de preparação de dados
func NewDataPreparationStep() *DataPreparationStep {
	return &DataPreparationStep{
		BaseStep: NewBaseStep(
			"data-preparation",
			"Prepara dados de processamento para geração de relatórios",
			30*time.Second,
		),
	}
}

// Execute executa preparação dos dados
func (s *DataPreparationStep) Execute(ctx *WorkflowContext) error {
	ctx.Logger.Info("Preparando dados para geração de relatórios")
	
	// Verificar se há dados de processamento disponíveis
	processedData, exists := ctx.Get("processing_results")
	if !exists {
		return fmt.Errorf("dados de processamento não encontrados")
	}
	
	// Preparar dados básicos
	processingData := map[string]interface{}{
		"processed_at":   time.Now(),
		"workflow_id":    ctx.ExecutionID,
		"workflow_name":  ctx.WorkflowName,
		"original_data":  processedData,
	}
	
	// Adicionar dados de anomalias se disponível
	if anomalyReport, exists := ctx.Get("anomaly_report"); exists {
		processingData["anomaly_report"] = anomalyReport
	}
	
	// Armazenar dados preparados
	ctx.Set("prepared_data", processingData)
	
	ctx.Logger.Info("Dados preparados para geração de relatórios")
	
	return nil
}

// ExecutiveReportStep gera relatório executivo
type ExecutiveReportStep struct {
	*BaseStep
	generator ReportGenerator
	config    *ReportingWorkflowConfig
}

// NewExecutiveReportStep cria step de relatório executivo
func NewExecutiveReportStep(generator ReportGenerator, config *ReportingWorkflowConfig) *ExecutiveReportStep {
	return &ExecutiveReportStep{
		BaseStep: NewBaseStep(
			"executive-report",
			"Gera relatório executivo com insights automáticos",
			60*time.Second,
		),
		generator: generator,
		config:    config,
	}
}

// Execute gera relatório executivo
func (s *ExecutiveReportStep) Execute(ctx *WorkflowContext) error {
	if !s.config.AutoGenerateExecutive {
		ctx.Logger.Debug("Geração de relatório executivo desabilitada")
		return nil
	}
	
	ctx.Logger.Info("Gerando relatório executivo")
	
	// Obter dados preparados
	preparedData, exists := ctx.Get("prepared_data")
	if !exists {
		return fmt.Errorf("dados preparados não encontrados")
	}
	
	// Gerar relatórios nos formatos configurados
	var reports []interface{}
	
	for _, format := range s.config.DefaultFormats {
		ctx.Logger.Debug("Gerando relatório executivo em formato %s", format)
		
		if s.generator != nil {
			report, err := s.generator.GenerateExecutiveReport(preparedData, format)
			if err != nil {
				ctx.Logger.Error("Erro ao gerar relatório executivo (%s): %v", format, err)
				continue
			}
			reports = append(reports, report)
		} else {
			// Fallback: criar relatório básico
			basicReport := map[string]interface{}{
				"type":         "executive",
				"format":       format,
				"generated_at": time.Now(),
				"data":         preparedData,
			}
			reports = append(reports, basicReport)
		}
		
		ctx.Logger.Info("Relatório executivo gerado com sucesso (%s)", format)
	}
	
	if len(reports) == 0 {
		return fmt.Errorf("falha ao gerar relatórios executivos em todos os formatos")
	}
	
	// Armazenar relatórios no contexto
	ctx.Set("executive_reports", reports)
	ctx.SetResult(s.Name(), fmt.Sprintf("%d relatórios executivos gerados", len(reports)))
	
	return nil
}

// CanSkip verifica se pode pular o step
func (s *ExecutiveReportStep) CanSkip(ctx *WorkflowContext) bool {
	return !s.config.AutoGenerateExecutive
}

// DetailedReportStep gera relatório detalhado
type DetailedReportStep struct {
	*BaseStep
	generator ReportGenerator
	config    *ReportingWorkflowConfig
}

// NewDetailedReportStep cria step de relatório detalhado
func NewDetailedReportStep(generator ReportGenerator, config *ReportingWorkflowConfig) *DetailedReportStep {
	return &DetailedReportStep{
		BaseStep: NewBaseStep(
			"detailed-report",
			"Gera relatório detalhado com dados completos",
			90*time.Second,
		),
		generator: generator,
		config:    config,
	}
}

// Execute gera relatório detalhado
func (s *DetailedReportStep) Execute(ctx *WorkflowContext) error {
	if !s.config.AutoGenerateDetailed {
		ctx.Logger.Debug("Geração de relatório detalhado desabilitada")
		return nil
	}
	
	ctx.Logger.Info("Gerando relatório detalhado")
	
	// Obter dados preparados
	preparedData, exists := ctx.Get("prepared_data")
	if !exists {
		return fmt.Errorf("dados preparados não encontrados")
	}
	
	// Gerar relatório detalhado (tipicamente em JSON ou Excel)
	detailedFormats := []string{"json", "excel"}
	var reports []interface{}
	
	for _, format := range detailedFormats {
		if containsFormat(s.config.DefaultFormats, format) {
			if s.generator != nil {
				report, err := s.generator.GenerateDetailedReport(preparedData, format)
				if err != nil {
					ctx.Logger.Error("Erro ao gerar relatório detalhado (%s): %v", format, err)
					continue
				}
				reports = append(reports, report)
			}
		}
	}
	
	ctx.Set("detailed_reports", reports)
	ctx.SetResult(s.Name(), fmt.Sprintf("%d relatórios detalhados gerados", len(reports)))
	
	return nil
}

// CanSkip verifica se pode pular o step
func (s *DetailedReportStep) CanSkip(ctx *WorkflowContext) bool {
	return !s.config.AutoGenerateDetailed
}

// AnomalyReportStep gera relatório de anomalias
type AnomalyReportStep struct {
	*BaseStep
	generator ReportGenerator
	config    *ReportingWorkflowConfig
}

// NewAnomalyReportStep cria step de relatório de anomalias
func NewAnomalyReportStep(generator ReportGenerator, config *ReportingWorkflowConfig) *AnomalyReportStep {
	return &AnomalyReportStep{
		BaseStep: NewBaseStep(
			"anomaly-report",
			"Gera relatório de anomalias se detectadas",
			45*time.Second,
		),
		generator: generator,
		config:    config,
	}
}

// Execute gera relatório de anomalias
func (s *AnomalyReportStep) Execute(ctx *WorkflowContext) error {
	if !s.config.AutoGenerateAnomaly {
		ctx.Logger.Debug("Geração de relatório de anomalias desabilitada")
		return nil
	}
	
	// Verificar se há dados preparados
	preparedData, exists := ctx.Get("prepared_data")
	if !exists {
		return fmt.Errorf("dados preparados não encontrados")
	}
	
	// Verificar se há dados de anomalias
	preparedMap, ok := preparedData.(map[string]interface{})
	if !ok {
		return fmt.Errorf("formato de dados preparados inválido")
	}
	
	anomalyReport, hasAnomalies := preparedMap["anomaly_report"]
	if !hasAnomalies || anomalyReport == nil {
		ctx.Logger.Info("Nenhuma anomalia detectada - pulando geração de relatório")
		return nil
	}
	
	ctx.Logger.Info("Gerando relatório de anomalias")
	
	// Gerar relatório de anomalias (tipicamente em texto e JSON)
	anomalyFormats := []string{"text", "json"}
	var reports []interface{}
	
	for _, format := range anomalyFormats {
		if s.generator != nil {
			report, err := s.generator.GenerateAnomalyReport(preparedData, format)
			if err != nil {
				ctx.Logger.Error("Erro ao gerar relatório de anomalias (%s): %v", format, err)
				continue
			}
			reports = append(reports, report)
		}
	}
	
	ctx.Set("anomaly_reports", reports)
	ctx.SetResult(s.Name(), fmt.Sprintf("%d relatórios de anomalias gerados", len(reports)))
	
	// Marcar flag de anomalias críticas se necessário
	ctx.Set("critical_anomalies_detected", true)
	ctx.Logger.Warn("Anomalias detectadas - notificação de alta prioridade será enviada")
	
	return nil
}

// CanSkip verifica se pode pular o step
func (s *AnomalyReportStep) CanSkip(ctx *WorkflowContext) bool {
	return !s.config.AutoGenerateAnomaly
}

// ReportSummaryStep consolida resumo de todos os relatórios
type ReportSummaryStep struct {
	*BaseStep
}

// NewReportSummaryStep cria step de resumo de relatórios
func NewReportSummaryStep() *ReportSummaryStep {
	return &ReportSummaryStep{
		BaseStep: NewBaseStep(
			"report-summary",
			"Consolida resumo de todos os relatórios gerados",
			15*time.Second,
		),
	}
}

// Execute consolida resumo dos relatórios
func (s *ReportSummaryStep) Execute(ctx *WorkflowContext) error {
	ctx.Logger.Info("Consolidando resumo dos relatórios gerados")
	
	summary := make(map[string]interface{})
	summary["generated_at"] = time.Now()
	summary["workflow_id"] = ctx.ExecutionID
	
	totalReports := 0
	
	// Contar relatórios executivos
	if execReports, exists := ctx.Get("executive_reports"); exists {
		if reports, ok := execReports.([]interface{}); ok {
			summary["executive_reports_count"] = len(reports)
			totalReports += len(reports)
		}
	}
	
	// Contar relatórios detalhados
	if detReports, exists := ctx.Get("detailed_reports"); exists {
		if reports, ok := detReports.([]interface{}); ok {
			summary["detailed_reports_count"] = len(reports)
			totalReports += len(reports)
		}
	}
	
	// Contar relatórios de anomalias
	if anomReports, exists := ctx.Get("anomaly_reports"); exists {
		if reports, ok := anomReports.([]interface{}); ok {
			summary["anomaly_reports_count"] = len(reports)
			totalReports += len(reports)
		}
	}
	
	summary["total_reports_generated"] = totalReports
	
	// Adicionar informações de anomalias críticas se houver
	if criticalDetected, exists := ctx.Get("critical_anomalies_detected"); exists && criticalDetected.(bool) {
		summary["critical_anomalies_detected"] = true
		summary["priority_level"] = "high"
	} else {
		summary["priority_level"] = "normal"
	}
	
	ctx.Set("reporting_summary", summary)
	ctx.SetResult(s.Name(), summary)
	
	ctx.Logger.Info("Resumo consolidado: %d relatórios gerados", totalReports)
	
	return nil
}

// NotificationStep envia notificações sobre os relatórios gerados
type NotificationStep struct {
	*BaseStep
	config *ReportingWorkflowConfig
}

// NewNotificationStep cria step de notificação
func NewNotificationStep(config *ReportingWorkflowConfig) *NotificationStep {
	return &NotificationStep{
		BaseStep: NewBaseStep(
			"notification",
			"Envia notificações sobre os relatórios gerados",
			30*time.Second,
		),
		config: config,
	}
}

// Execute envia notificações
func (s *NotificationStep) Execute(ctx *WorkflowContext) error {
	if !s.config.NotifyStakeholders {
		ctx.Logger.Debug("Notificações desabilitadas")
		return nil
	}
	
	ctx.Logger.Info("Enviando notificações sobre relatórios gerados")
	
	// Obter resumo dos relatórios
	summaryData, exists := ctx.Get("reporting_summary")
	if !exists {
		ctx.Logger.Warn("Resumo de relatórios não encontrado")
		return nil
	}
	
	summary, ok := summaryData.(map[string]interface{})
	if !ok {
		return fmt.Errorf("formato de resumo inválido")
	}
	
	// Por enquanto, apenas log da notificação
	// Em uma implementação completa, isso enviaria emails, webhooks, etc.
	priorityLevel := summary["priority_level"].(string)
	totalReports := summary["total_reports_generated"].(int)
	
	if priorityLevel == "high" {
		ctx.Logger.Warn("🚨 RELATÓRIOS COM ANOMALIAS CRÍTICAS GERADOS!")
		ctx.Logger.Warn("Total de relatórios: %d", totalReports)
		ctx.Logger.Warn("AÇÃO REQUERIDA: Revisar anomalias críticas imediatamente")
	} else {
		ctx.Logger.Info("✅ Relatórios gerados com sucesso")
		ctx.Logger.Info("Total de relatórios: %d", totalReports)
	}
	
	// Simular envio de notificação
	notification := map[string]interface{}{
		"sent_at":         time.Now(),
		"priority":        priorityLevel,
		"total_reports":   totalReports,
		"recipients_count": len(s.config.EmailRecipients),
		"status":          "sent",
	}
	
	ctx.Set("notification_result", notification)
	ctx.SetResult(s.Name(), "Notificações enviadas com sucesso")
	
	return nil
}

// CanSkip verifica se pode pular o step
func (s *NotificationStep) CanSkip(ctx *WorkflowContext) bool {
	return !s.config.NotifyStakeholders || len(s.config.EmailRecipients) == 0
}

// Helper functions

// containsFormat verifica se uma lista contém um formato específico
func containsFormat(formats []string, format string) bool {
	for _, f := range formats {
		if f == format {
			return true
		}
	}
	return false
}