// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConsolidatedData() {
  return window['go']['main']['App']['GetConsolidatedData']();
}

export function GetSystemPrompt() {
  return window['go']['main']['App']['GetSystemPrompt']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RealizarAnaliseOrquestrada(arg1) {
  return window['go']['main']['App']['RealizarAnaliseOrquestrada'](arg1);
}

export function SelecionarDiretorio() {
  return window['go']['main']['App']['SelecionarDiretorio']();
}

export function SetChatContext() {
  return window['go']['main']['App']['SetChatContext']();
}

export function SetDiretorioPlanilhas(arg1) {
  return window['go']['main']['App']['SetDiretorioPlanilhas'](arg1);
}

export function SetOllamaConfig(arg1) {
  return window['go']['main']['App']['SetOllamaConfig'](arg1);
}

export function SetOpenAIKey(arg1) {
  return window['go']['main']['App']['SetOpenAIKey'](arg1);
}

export function TestExcelReading() {
  return window['go']['main']['App']['TestExcelReading']();
}

export function TestOllamaConnection(arg1) {
  return window['go']['main']['App']['TestOllamaConnection'](arg1);
}

export function TestOpenAIKey(arg1) {
  return window['go']['main']['App']['TestOpenAIKey'](arg1);
}
