// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function SelecionarDiretorio():Promise<string>;

export function SetDiretorioPlanilhas(arg1:string):Promise<boolean>;

export function TestExcelReading():Promise<string>;
