// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../../runtime/ipc';

export function Greet(arg1) {
    return ipc.send('main.App.Greet', arg1);
}

export function RealizarAnaliseOrquestrada(arg1) {
    return ipc.send('main.App.RealizarAnaliseOrquestrada', arg1);
}

export function SelecionarDiretorio() {
    return ipc.send('main.App.SelecionarDiretorio');
}

export function SetDiretorioPlanilhas(arg1) {
    return ipc.send('main.App.SetDiretorioPlanilhas', arg1);
}

export function TestExcelReading() {
    return ipc.send('main.App.TestExcelReading');
}
