// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {modelo} from '../models';

export function AskAI(arg1:string):Promise<string>;

export function CancelWorkflow():Promise<void>;

export function ClearAgentLogs():Promise<void>;

export function GetAgentStatus():Promise<main.AgentStatus>;

export function GetConfig():Promise<config.Config>;

export function GetConsolidatedData():Promise<Record<string, modelo.Colaborador>>;

export function GetSystemPrompt():Promise<string>;

export function GetWorkflowHistory():Promise<Array<main.WorkflowExecution>>;

export function Greet(arg1:string):Promise<string>;

export function RealizarAnaliseOrquestrada(arg1:string):Promise<string>;

export function SelecionarDiretorio():Promise<string>;

export function SetChatContext():Promise<void>;

export function SetDiretorioPlanilhas(arg1:string):Promise<boolean>;

export function SetOllamaConfig(arg1:config.OllamaConfig):Promise<void>;

export function SetOpenAIKey(arg1:string):Promise<void>;

export function StartWorkflow(arg1:main.WorkflowStartRequest):Promise<void>;

export function StopWorkflow():Promise<void>;

export function TestExcelReading():Promise<string>;

export function TestOllamaConnection(arg1:config.OllamaConfig):Promise<boolean>;

export function TestOpenAIKey(arg1:string):Promise<boolean>;
