// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelecionarDiretorio() {
  return window['go']['main']['App']['SelecionarDiretorio']();
}

export function SetDiretorioPlanilhas(arg1) {
  return window['go']['main']['App']['SetDiretorioPlanilhas'](arg1);
}

export function TestExcelReading() {
  return window['go']['main']['App']['TestExcelReading']();
}
