// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {predicoes} from '../models';
import {intelligence} from '../models';
import {time} from '../models';
import {main} from '../models';
import {config} from '../models';
import {modelo} from '../models';

export function AddHistoricalData(arg1:predicoes.HistoricalVRData):Promise<void>;

export function AnalyzePatterns(arg1:string):Promise<Array<intelligence.ConsumptionPattern>>;

export function AskAI(arg1:string):Promise<string>;

export function AskAIBasic(arg1:string):Promise<string>;

export function CancelWorkflow():Promise<void>;

export function ClearAgentLogs():Promise<void>;

export function ClearKnowledgeCache():Promise<void>;

export function CreateHistoricalDataFromCurrent(arg1:string,arg2:time.Time):Promise<void>;

export function DetectTrends(arg1:string):Promise<intelligence.TrendAnalysisResult>;

export function FixOllamaConfig():Promise<void>;

export function GenerateForecast(arg1:string,arg2:number):Promise<predicoes.ConsumptionForecast>;

export function GenerateRecommendations(arg1:string):Promise<intelligence.RecommendationSuite>;

export function GetAgentStatus():Promise<main.AgentStatus>;

export function GetAgentStatusSimple():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetConsolidatedData():Promise<Record<string, modelo.Colaborador>>;

export function GetHistoricalData():Promise<Array<predicoes.HistoricalVRData>>;

export function GetKnowledgeCacheMetrics():Promise<Record<string, any>>;

export function GetPredictiveAnalysisSummary(arg1:string):Promise<Record<string, any>>;

export function GetSystemPrompt():Promise<string>;

export function GetWorkflowHistory():Promise<Array<main.WorkflowExecution>>;

export function Greet(arg1:string):Promise<string>;

export function IsAgentEnabled():Promise<boolean>;

export function IsKnowledgeCacheEnabled():Promise<boolean>;

export function PredictTrends(arg1:string):Promise<predicoes.Prediction>;

export function RealizarAnaliseOrquestrada(arg1:string):Promise<string>;

export function SelecionarDiretorio():Promise<string>;

export function SetAgentEnabled(arg1:boolean):Promise<void>;

export function SetChatContext():Promise<void>;

export function SetDiretorioPlanilhas(arg1:string):Promise<boolean>;

export function SetKnowledgeCacheEnabled(arg1:boolean):Promise<void>;

export function SetOllamaConfig(arg1:config.OllamaConfig):Promise<void>;

export function SetOpenAIKey(arg1:string):Promise<void>;

export function StartWorkflow(arg1:main.WorkflowStartRequest):Promise<void>;

export function StopWorkflow():Promise<void>;

export function TestExcelReading():Promise<string>;

export function TestOllamaConnection(arg1:config.OllamaConfig):Promise<boolean>;

export function TestOpenAIKey(arg1:string):Promise<boolean>;
